ignore_colors = [
    #000000, # filter all black, DO NOT USE "#"!!!
]
width = 1000
height = 1000
add-x = 500
add-y = 500

default_prio = 120 # priority: higher number = higher chance of being placed


# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127

[[structure]]
name = "jules_pikachu"
file = "jules_pikachu.png"
startx = -7
starty = -435
priority = 127

[[structure]]
name = "ottifant"
file = "ottifant.png"
startx = 340
starty = -450
priority = 127

[[structure]]
name = "paragraf_eins"
file = "paragraf_eins.png"
startx = 170
starty = -450
priority = 127

[[structure]]
name = "spezi"
file = "spezi.png"
startx = 300
starty = -450
priority = 127

[[structure]]
name = "TUEV"
file = "TUEV.png"
startx = -400
starty = -450
priority = 127

[[structure]]
name = "JojoCroc"
file = "JojoCroc.png"
startx = 125
starty = -450
priority = 127

[[structure]]
name = "subredditstra"
file = "subredditstra.png"
startx = -500
starty = -420
priority = 127

[[structure]]
name = "getraenke"
file = "getraenke.png"
startx = -280
starty = -448
priority = 127

[[structure]]
name = "leibniz_keks"
file = "leibniz_keks.png"
startx = 50
starty = -448
priority = 127
