ignored_colors = []
allowed_colors = ["FF4500","FFA800","FFD635","00A368","7EED56","2450A4","3690EA","51E9F4","811E9F","B44AC0","FF99AA","9C6926","000000","898D90","D4D7D9","FFFFFF"]
width = 2000
height = 1500
add-x = 1000
add-y = 1000
default_prio = 120

[[structure]]
name = "skandinavien"
file = "skandinavien.png"
startx = -1000
starty = -500
priority = 127
overlay_only = true
disabled = true

[[structure]]
name = "subredditstra"
file = "subredditstra.png"
startx = -1000
starty = -450
priority = 127

[[structure]]
name = "a380"
file = "a380.png"
startx = -969
starty = -416
priority = 128

[[structure]]
name = "overhead"
file = "overhead.png"
startx = -902
starty = -440
priority = 127

[[structure]]
name = "de_nl_love"
file = "de_nl_love.png"
startx = -885
starty = -500
priority = 127

[[structure]]
name = "was_ist_was"
file = "was_ist_was.png"
startx = -788
starty = -429
priority = 127

[[structure]]
name = "trabi_mauer"
file = "trabi_mauer.png"
startx = -731
starty = -442
priority = 127

[[structure]]
name = "hanf_karl"
file = "hanf_karl.png"
startx = -671
starty = -445
priority = 127

[[structure]]
name = "pettersson_findus"
file = "pettersson_findus.png"
startx = -612
starty = -450
priority = 127

[[structure]]
name = "tagesschau"
file = "tagesschau.png"
startx = -515
starty = -448
priority = 127

[[structure]]
name = "pfandrec"
file = "pfandrec.png"
startx = -454
starty = -441
priority = 127

[[structure]]
name = "kippfenster"
file = "kippfenster.png"
startx = -426
starty = -432
priority = 127

[[structure]]
name = "TUEV"
file = "TUEV.png"
startx = -400
starty = -450
priority = 127

[[structure]]
name = "cash"
file = "cash.png"
startx = -344
starty = -428
priority = 127

[[structure]]
name = "ying_yang_nl"
file = "ying_yang_nl.png"
startx = -344
starty = -467
priority = 127

[[structure]]
name = "din_fckafd_kombi"
file = "din_fckafd_kombi.png"
startx = -312
starty = -458
priority = 127

[[structure]]
name = "getraenke"
file = "getraenke.png"
startx = -231
starty = -450
priority = 127

[[structure]]
name = "spez_adler_kombi"
file = "spez_adler_kombi.png"
startx = -137
starty = -449
priority = 127

[[structure]]
name = "nospeed"
file = "nospeed.png"
startx = -20
starty = -450
priority = 127

[[structure]]
name = "jules_pikachu"
file = "jules_pikachu.png"
startx = -3
starty = -430
priority = 127

[[structure]]
name = "mango"
file = "mango.png"
startx = 9
starty = -449
priority = 127

[[structure]]
name = "leibniz_keks"
file = "leibniz_keks.png"
startx = 50
starty = -448
priority = 127

[[structure]]
name = "bikenl"
file = "bikenl.png"
startx = 29
starty = -466
priority = 127

[[structure]]
name = "berliner"
file = "berliner.png"
startx = 51
starty = -424
priority = 127

[[structure]]
name = "pombaer"
file = "pombaer.png"
startx = 89
starty = -437
priority = 127

[[structure]]
name = "yoyo_croc"
file = "yoyo_croc.png"
startx = 125
starty = -450
priority = 127

[[structure]]
name = "paragraf_eins"
file = "paragraf_eins.png"
startx = 170
starty = -450
priority = 127

[[structure]]
name = "ketchup"
file = "ketchup.png"
startx = 269
starty = -441
priority = 127

[[structure]]
name = "ottifant_spezi"
file = "ottifant_spezi.png"
startx = 299
starty = -450
priority = 127

[[structure]]
name = "radiergummi"
file = "radiergummi.png"
startx = 337
starty = -415
priority = 127

[[structure]]
name = "curry"
file = "curry.png"
startx = 399
starty = -458
priority = 127

[[structure]]
name = "maggi"
file = "maggi.png"
startx = 469
starty = -449
priority = 127

[[structure]]
name = "brudi_muss_mal"
file = "brudi_muss_mal.png"
startx = 483
starty = -449
priority = 127

[[structure]]
name = "kasette"
file = "kasette.png"
startx = 550
starty = -463
priority = 127

[[structure]]
name = "sandale"
file = "sandale.png"
startx = 602
starty = -449
priority = 127

[[structure]]
name = "aspen_schuessel."
file = "aspen_schuessel.png"
startx = 639
starty = -441
priority = 127

[[structure]]
name = "d_ticket"
file = "d_ticket.png"
startx = 771
starty = -418
priority = 127

[[structure]]
name = "baustelle"
file = "baustelle.png"
startx = 818
starty = -447
priority = 127

[[structure]]
name = "late_db"
file = "late_db.png"
startx = 855
starty = -451
priority = 127

[[structure]]
name = "pumuckl"
file = "pumuckl.png"
startx = 725
starty = -435
priority = 127

[[structure]]
name = "rettungsfahrzeuge"
file = "rettungsfahrzeuge.png"
startx = 854
starty = -426
priority = 127

[[structure]]
name = "panzer"
file = "panzer.png"
startx = -30
starty = -174
priority = 127
disabled = true

[[structure]]
name = "alltrains"
file = "alltrains.png"
startx = -1000
starty = -392
priority = 127

[[structure]]
name = "canada_left"
file = "canada_left.png"
startx = 90
starty = 165
priority = 127
overlay_only = false
disabled = true

[[structure]]
name = "ukrainetemp"
file = "ukrainetemp.png"
startx = -1000
starty = -500
priority = 127
overlay_only = false
disabled = true

[[structure]]
name = "netherlands"
file = "netherlands.png"
startx = -1000
starty = -500
priority = 126
overlay_only = false

[[structure]]
name = "nett_hier"
file = "nett_hier.png"
startx = 319
starty = -496
priority = 127
overlay_only = false
disabled = true

[[structure]]
name = "was"
file = "was.png"
startx = 682
starty = -458
priority = 127
overlay_only = false
disabled = true

[[structure]]
name = "transplace_teil1"
file = "transplace_teil1.png"
startx = 48
starty = -3
priority = 127
overlay_only = true

[[structure]]
name = "transplace_teil2"
file = "transplace_teil2.png"
startx = -632
starty = -184
priority = 127
overlay_only = true

[[structure]]
name = "canada_right_without_small_flags"
file = "canada_right_without_small_flags.png"
disabled = true
startx = 681
starty = -114
priority = 126
overlay_only = false

[[structure]]
name = "canada_right"
file = "canada_right.png"
disabled = true
startx = 680
starty = -118
priority = 127
overlay_only = false
